//##############################################################################
//## Copyright (C) 2002-2004 Marco Aurelio Stelmar Netto <stelmar@cpad.pucrs.br>
//##
//##  This program is free software; you can redistribute it and/or modify
//##  it under the terms of the GNU General Public License as published by
//##  the Free Software Foundation; either version 2 of the License, or
//##  (at your option) any later version.
//##
//##  This program is distributed in the hope that it will be useful,
//##  but WITHOUT ANY WARRANTY; without even the implied warranty of
//##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//##  GNU General Public License for more details.
//##
//##  You should have received a copy of the GNU General Public License
//##  along with this program; if not, write to the Free Software
//##  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
//#############################################################################
//## Show statistics of usage of a cluster
//#############################################################################

#include "common.h"

#define ADD_TIME 0
#define DEL_TIME 1

typedef struct 
{
  int time,nnodes;
  char user[_POSIX_LOGIN_NAME_MAX];
}SStat;

int nusers=0;
SStat *crstat;
long int total_usage=0;

void crstat_getargs(int argc,char **argv,char *logfile,int *ndays,int *nnodes);
void crstat_usage();
void get_time(char *user,int time, int nnodes, char oper);
int  month2ndays(char *month);
void stat_bubble();
//##############################################################################
//## Calculate some statistics data
//##############################################################################
int main(int argc, char **argv)
{
  FILE *fp;
  char buf[S_LINEF],buf1[S_LINEF],logfile[S_PATH];
  int time,i;
  int ndays=0;
  int nnodes=0;
  int nclusternodes=0;
  char firstline=TRUE; 

  crstat_getargs(argc,argv,logfile,&ndays,&nclusternodes);

  crstat=(SStat*)malloc(sizeof(SStat));

  if( (fp=fopen(logfile,"r")) == NULL)
     ERROR("Problems to open file %s\n",logfile);
  dprintf("User    Time    Nnodes\n");

  while(fgets(buf,sizeof(buf),fp))
  { 
     buf[strlen(buf)-1]=0;
     if(firstline)
     {  if(!ndays)
        {  sscanf(buf,"%s",buf1);
           ndays=month2ndays(buf1);
        }
        firstline=FALSE;  
     }    
     if(strstr(buf,"START USER")!=NULL)
     {  sscanf(buf,"%*s %*s %*s %*s %*s %*s %*s %s %*s %d %*s %d",buf1,
               &time,&nnodes);
        //printf("<%8s> <%8d> <%8d> \n",buf1,time,nnodes);
        get_time(buf1,time,nnodes,ADD_TIME); 
     }
     else if(strstr(buf,"CANCEL USER")!=NULL)
     {  sscanf(buf,"%*s %*s %*s %*s %*s %*s %*s %s %*s %d %*s %d",buf1,
               &time,&nnodes);
        //printf("<%8s> <%8d> <%8d> \n",buf1,time,nnodes);
        get_time(buf1,time,nnodes,DEL_TIME); 
     }
  }
  stat_bubble();
  for(i=0;i<nusers;i++)
     printf("%03d> User: %-10s Time: %-7d minutes\n",i+1,crstat[i].user,
            crstat[i].time);

  printf("AVERAGE UTILIZATION: %.3f %%\n",
         100.0*total_usage/((float)nclusternodes*ndays*24*60));

  return 0;
}
//##############################################################################
//## Parser of the command line
//##############################################################################
void crstat_getargs(int argc,char **argv,char *logfile,int *ndays,int *nnodes)
{
  char opnnodes=FALSE,opndays=FALSE,oplog=FALSE;

  while (--argc)
  {  argv++;
     if( !strcmp(argv[0],"-f") )
     {  if( !--argc || oplog)
           crstat_usage();
        else
        {  argv++;
           dprintf("Log: %s\n",argv[0]);
           strcpy(logfile,argv[0]);
           oplog=TRUE;
        }
     }
     else if( !strcmp(argv[0],"-n") )
     {  if( !--argc || opnnodes)
           crstat_usage();
        else
        {  argv++;
           dprintf("Nnodes: %s\n",argv[0]);
           *nnodes=atoi(argv[0]);
           opnnodes=TRUE;
        }
     }
     else if( !strcmp(argv[0],"-d") )
     {  if( !--argc || opndays)
             crstat_usage();
        else
        {  argv++;
           dprintf("Days: %s\n",argv[0]);
           *ndays=atoi(argv[0]);
           opndays=TRUE;
        }
     }
     else crstat_usage();
  }

  if(!oplog || !opnnodes)
    crstat_usage(); 
}
//##############################################################################
//## Usage of the crstat command
//##############################################################################
void crstat_usage()
{
  printf("Crono v%s\n"
          "Usage: crstat -f <log> -n <nnodes> [ -d <ndays> ]\n"
          "       crqview --help\n\n"
          "\t-f <log>\t\t: Log file generated by Crono\n"
          "\t-n <nnodes>\t\t: Number of nodes the cluster has\n"
          "\t-d <ndays>\t\t: Number of days of the month\n"
          "\t--help\t\t\t: Display this help and exit\n\n"
          ,CRONO_VERSION);
  exit(1);
}
//##############################################################################
//## Use the information from the log file
//##############################################################################
void get_time(char *user,int time, int nnodes, char oper)
{
  int i;
  char flag=FALSE;

  for(i=0;i<nusers;i++)
    if(!strcmp(crstat[i].user,user))
    {   flag=TRUE;
        break;
    }

  if(!flag) //it is a new user
  {  crstat=(SStat*)realloc(crstat,sizeof(SStat)*(nusers+1));
     crstat[i].time=0;
     strcpy(crstat[i].user,user);
     nusers++;
  }

  if(oper==ADD_TIME)
  {
     crstat[i].time+=time;
     total_usage+=time*nnodes;
  }
  else
  {
     crstat[i].time-=time;
     total_usage-=time*nnodes;
  }
}
//##############################################################################
//## Return the number of days of the 'month' of the current year
//##############################################################################
int month2ndays(char *month)
{
  time_t timet;
  struct tm t;
  char bissextile;  

  if(!strcmp("Jan",month) || !strcmp("Mar",month) || !strcmp("May",month) ||
     !strcmp("Jul",month) || !strcmp("Aug",month) || !strcmp("Oct",month) ||
     !strcmp("Dec",month))
     return 31;

  else if(strcmp("Feb",month))
     return 30;

  timet=time(NULL);
  memcpy(&t,localtime(&timet),sizeof(struct tm));
  t.tm_sec=0;
  t.tm_year+=1900;

  bissextile = (( (!( t.tm_year%4)) && (t.tm_year%100)) || ( !(t.tm_year%400)));

  if(bissextile)
     return 29;
  else return 28;
}
//##############################################################################
//## Sort statistics data
//##############################################################################
void stat_bubble()
{
  int i,j;
  SStat temp;

  for (i=0; i<nusers-1; i++)
    for (j=0; j<nusers-1-i; j++)
       if (crstat[j+1].time > crstat[j].time)
       {  temp = crstat[j];
          crstat[j] = crstat[j+1];
          crstat[j+1] = temp;
       }
}
//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
