###############################################################################
# Example of a config file of a cluster called 'tropical'
# 
# CLUSTER: Tropical
#
###############################################################################

# Server ports
amport=7011
rmport=7022
nmport=7040

# Server hosts
amhost=localhost
rmhost=localhost

# Number of users that can share the nodes at the same time
share=2

# Single Option (off-> there is a cluster available)
#               (on-> there is not a cluster available)
single=off

# PAM support (Pluggable Authentication Modules)
pam=on

#Connection Timeout in seconds
conntimeout=1

# Timeout of Master pre-processing script
tmpreps=2
  
# Timeout of Master post-processing script
tmpostps=2

# Log File
logfile=/usr/local/var/log/crono_tropical.log

# Queue File 
queuefile=/usr/local/var/queues/crono_tropical.queue

# Process IDs Directory
piddir=/var/run/

